/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Blog: typeof import('./src/components/MainPage/Blog/Blog.vue')['default']
    Carrito: typeof import('./src/components/MainPage/Carrito/Carrito.vue')['default']
    IBiArrowDown: typeof import('~icons/bi/arrow-down')['default']
    IBiArrowRepeat: typeof import('~icons/bi/arrow-repeat')['default']
    IBiArrowUp: typeof import('~icons/bi/arrow-up')['default']
    IBiCart: typeof import('~icons/bi/cart')['default']
    IBiEnvelope: typeof import('~icons/bi/envelope')['default']
    IBiEye: typeof import('~icons/bi/eye')['default']
    IBiFacebook: typeof import('~icons/bi/facebook')['default']
    IBiFileEarmarkArrowUp: typeof import('~icons/bi/file-earmark-arrow-up')['default']
    IBiInstagram: typeof import('~icons/bi/instagram')['default']
    IBiList: typeof import('~icons/bi/list')['default']
    IBiSave: typeof import('~icons/bi/save')['default']
    IBiTelephone: typeof import('~icons/bi/telephone')['default']
    IBiTrash: typeof import('~icons/bi/trash')['default']
    IBiUpload: typeof import('~icons/bi/upload')['default']
    IBiYoutube: typeof import('~icons/bi/youtube')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MenuLanding: typeof import('./src/components/MainPage/MenuLanding/MenuLanding.vue')['default']
    Planes: typeof import('./src/components/Planes/Planes.vue')['default']
    Productos: typeof import('./src/components/Productos/Productos.vue')['default']
    RefiereGana: typeof import('./src/components/MainPage/RefiereGana/RefiereGana.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ServiciosClaroHogar: typeof import('./src/components/MainPage/ServiciosClaro/ServiciosClaroHogar.vue')['default']
    ServiciosClaroPlanes: typeof import('./src/components/MainPage/ServiciosClaro/ServiciosClaroPlanes.vue')['default']
    SidebarMenu: typeof import('./src/components/Intranet/SidebarMenu/SidebarMenu.vue')['default']
  }
}
